### ISSUE TITLE
Bad request when using blanks in group names

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-identity#76]
**Version Info**
18.1 SSO (13.11.2019)

**Describe the bug**
Creating groups using blanks in groups names leads to HTTP 400

**How to Reproduce**
See https://github.com/servicecatalog/oscm/issues/464

**Observed behavior**
HTTP 400 

**Expected behavior**
HTTP 200

**Screenshots**
NA

**Additional context**
11/13/2019_18:33:32.849 FSP_INTS-BSS: INFO: ThreadID https-jsse-nio-8081-exec-7: IdentityClientHelper: 00025: Requesting: http://oscm-                                                      identity:9090/oscm-identity/tenants/default/groups finished with 400

11/13/2019_18:33:32.850 FSP_INTS-BSS: ERROR: ThreadID https-jsse-nio-8081-exec-7: IdentityClientHelper: 70325: Identity client request                                                        failed with Request_BadRequest : Invalid value specified for property 'mailNickname' of resource 'Group'.

**Comment by kowalczyka** [comment]
I confirmed the issue - behind the scenes mailNickname is set with the same value as the name of the group. As we now adapt the endpoint so that blanks can be used in group name, mailNickname must be filled with some other value (as it does not allow blanks). This field is required so we have two solutions here:

1. To pass additional value for this field when requesting create group endpoint (this would require changes in identity client and adapting the endpoint for this).
2. To simply hardcode this value within the create group endpoint.

Whatever option we decide , we would need to agree on the value which this field should be filled with.

I would go with solution 2. 
@GoebelL please share your comments about this.

**Comment by GoebelL** [comment]
Option 2 is fine.
